nodejs:
  applicationPort: 3000
  aadIdentityName: my-time
  ingressHost: my-time.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'sdshmctspublic.azurecr.io/my-time/frontend:latest'
  keyVaults:
    my-time:
      resourceGroup: my-time-{{ .Values.global.environment }}-rg
      secrets:
        - AppInsightsInstrumentationKey
  environment:
    MY_TIME_API_URL: "http://my-time-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
